name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:


  argocd_sync:
    #needs: [docker_security_scan, kube_validation, kube_security_scan]
    runs-on: actions_runner_dev
    steps:
      - name: Deployment Sync
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          install -m 555 argocd-linux-amd64 ./argocd
          rm argocd-linux-amd64
          ./argocd login argocd-server.argocd.svc.cluster.local --insecure --username ${ARGOCD_USERNAME} --password ${ARGOCD_PASSWORD}
          ./argocd app actions run "desk-reservation-app-backend-go" restart --kind Deployment |& tee response.txt
          cat response.txt
          if [ -s response.txt ]; then exit 1; fi