apiVersion: v1
kind: Namespace
metadata:
  name: desk-reservation-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-go
  namespace: desk-reservation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-go
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-go: "go-instrumentation"
      labels:
        app: backend-go
    spec:
      containers:
      - name: backend-go
        image: gzarba/desk-reservation-app:backend-go
        ports:
        - containerPort: 5001
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: backend-go
  namespace: desk-reservation-app
spec:
  selector:
    app: backend-go
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: desk-reservation-app
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: gzarba/desk-reservation-app:postgres
        ports:
        - containerPort: 5432

